### ISSUE TITLE
Network name generated doesn't match with Pricer Project docker-compose

### ISSUE THREAD

**Issue by mtisserant** [flash-global/docker-dev-stack#4]
When I run these commands to start containers of Project based on docker-dev-stack like Pricer

```
1. worskpaces > cd docker-dev-stack
2. docker-dev-stack > docker-compose up
3. docker-dev-stack > cd ../Pricer2016Q2 
4. Pricer2016QA > docker-compose up
```

I have this error : docker-dev-stack : "ERROR: Network dockerdevstack_dev_stack_net declared as external, but could not be found. Please create the network manually using `docker network create dockerdevstack_dev_stack_net` and try again."

Response of command > docker network ls 
```
NETWORK ID          NAME                             DRIVER              SCOPE
3c645ac34f16        bridge                           bridge              local
5476bcfef209        docker-dev-stack_dev_stack_net   bridge              local
```

**Comment by Neofox** [comment]
`Network dockerdevstack_dev_stack_net [...] could not be found`
`5476bcfef209        docker-dev-stack_dev_stack_net   bridge              local`

You just have to use the correct name of the network and everything will work
